### ISSUE TITLE
Highlight mentions of you & mentions list

### ISSUE THREAD

**Issue by trymeouteh** [simplex-chat/simplex-chat#2161] opened 2023-04-09 02:37 UTC
In group chats were it gets long, it would be great to have messages that mentions you to be highlighted or bold, something to make them stick out when scrolling through the chat history

Also a mentions list and sender list would be nice, a way to search for messages in a chat that have mentions to someone and a way to search a chat for messages sent by a specific user.

**Comment by shumvgolove** [comment] 2023-04-26 13:18
Duplicate of https://github.com/simplex-chat/simplex-chat/issues/1681

**Closed by shumvgolove** 2023-04-26 13:18 UTC
