### ISSUE TITLE
Call are dropped after phone being locked for some time

### ISSUE THREAD

**Issue by x80486** [simplex-chat/simplex-chat#2128] opened 2023-04-02 13:20 UTC
I really cannot come up with a specific set of steps for this one, but so far, it happens intermittently, regardless of the network in use (WiFi and mobile) and signal strength.

Looks like when a call is placed, if the phone (after the screen is turned off) gets locked automatically, the call is dropped **when I tried to unlock the phone again**.

I can't correlate this with a certain (set of) action(s) because it happens some times only. I'm not sure if there is a time component involved, or if it's because I use the power button to start the unlock process...but in the end, the calls are dropped.

**Comment by epoberezkin** [comment] 2023-05-03 21:34
duplicate of #1045

**Closed by epoberezkin** 2023-05-03 21:34 UTC
Labels: bug, android
