### ISSUE TITLE
Draft messages / remember unsent messages

### ISSUE THREAD

**Issue by Mikaela** [simplex-chat/simplex-chat#1216] opened 2022-10-15 12:52 UTC
When leaving the chat without sending message, the currently typed message vanishes. I am experiencing this on both the Android and iOS apps.

Steps to reproduce in case they help:

1. Open a chat
2. Type something, but don't send it
3. Press back button / return to the chat list
4. Return to the first chat
5. The message is gone

**Comment by jr-simplex** [comment] 2022-10-15 14:06
Hi, it's not a bug really - it just hasn't been implemented yet. Still, thanks for feedback, we'll probably add this feature later at some point, it can indeed be inconvenient sometimes.

**Comment by ccxcz** [comment] 2022-10-24 10:04
I don't think that draft messages are any more (or less) secret than sent ones. So it would make sense to me to have at least the same retention period that chat backlog has.

I'd wager that if you need to erase drafts as soon as in a couple of minutes you would also require read-once messages (cf. #993, I don't see issue/feature request specific to single-view messages).

The current lack of draft support is especially annoying on Android as it can easily loose the message you are writing when switching between different apps while composing it.

**Comment by x80486** [comment] 2023-02-06 20:46
This can be closed as well since it's already implemented.

**Comment by shumvgolove** [comment] 2023-02-07 07:05
Thanks for the reminder!

**Closed by shumvgolove** 2023-02-07 07:05 UTC
Labels: enhancement, ios, android
