### ISSUE TITLE
Send read receipts (feature request taken from the Olvid app)

### ISSUE THREAD

**Issue by Wjxfi** [simplex-chat/simplex-chat#1773] opened 2023-01-17 01:41 UTC
![302281.jpg](https://user-images.githubusercontent.com/113500363/212791263-5040c546-2637-4f93-b631-015fc04a0b84.jpg)

**Comment by epoberezkin** [comment] 2023-01-17 09:09
Delivery receipts are definitely coming, read receipts are not planned yet - we do consider it an anti-feature that benefits app users more than the users (by fuelling addiction and anxiety, and by making users to find work-around to avoid read status being sent) - so it seems that everybody benefits from the absence of read receipts, and the request to never add them (even as opt in) is as frequent. So we will see, it's not planned for now.

**Comment by x80486** [comment] 2023-01-17 15:35
> Delivery receipts are definitely coming (with opt in or opt out - TBC), read receipts are not planned yet - we do consider it an anti-feature that benefits app owners more than the users

What's the one little tick then that the current messages have when they are sent? I thought that was the "delivery receipt" :thinking: ...which by the way, disappears after a while in some messages.

**Comment by epoberezkin** [comment] 2023-01-21 15:56
One tick means that the message is delivered from your client to the recipient's server - other messengers use the same semantics for ticks, since introduced by WhatsApp - 1 tick - safely stored on the server, so you no longer need internet connection, 2 ticks - delivered to the recipient's deivice, make them blue (or filled-in in case of Signal) - read.

> ...which by the way, disappears after a while in some messages.

Sounds like a bug - never saw that. We don't show it in groups though - maybe that's the case? The reason it's not shown in groups as it has more nuance to it - it can be delivered to some members' servers but not to all (and "all" would almost never happen in large groups), so we need to actually show the list of members to whose "message queues" (you can think of them as mailboxes) it's delivered.

Can you make a video of one tick disappearing? or at least a screenshot?

**Comment by x80486** [comment] 2023-01-21 16:22
OK, got it. What happens in my device is that sometimes when I flip it back and forth, some of the message boxes are "scrambled" and are moved a little bit to the left of the viewport, losing some of the initial characters of every line and the tick. I suspect it could be the toolkit used in this application — or something like that.

I'm sure you've seen that, so I was expecting that it would be fixed at some point.

**Comment by epoberezkin** [comment] 2023-01-21 19:17
Yes, we're aware of this layout engine problems - it happened because of super-hacky implementation of reverse lazy scroll that SwiftUI/UIKit do not support... Not sure if it's interesting, but for chat to work like it does everything has to be upside down (both the list and each item in it), and that makes context menus crazy, so they have to be re-implemented in even hackier way - and it causes all these layout issues.

The proper solution is to re-implement reverse scroll on the low level (we couldn't find a library that does it anywhere near comprehensively) - it's a substantial effort but we plan to do it.

I offered sponsoring the development of such library (reverse lazy scroll with variable size items) to several iOS open-source developers, but they all were busy elsewhere...

**Comment by trymeouteh** [comment] 2023-03-21 20:36
I would like to see opt in/out delivery receipts and read receipts

**Comment by shumvgolove** [comment] 2023-04-26 12:53
Duplicate of https://github.com/simplex-chat/simplex-chat/issues/687

**Closed as completed by shumvgolove** 2023-04-26 12:53 UTC
Labels: duplicate
