### ISSUE TITLE
[Feature Request] Show all media 

### ISSUE THREAD

**Issue by mika-nl** [simplex-chat/simplex-chat#1752] opened 2023-01-15 14:18 UTC
I would like to see the option to see all media in A chat. So that it is easier to search back a picture or file .

Now you can scroll the media but only the bit (last 100 posts) that is loaded . this is perfect for just scrolling through just gotten pictures .

I would like to see an extra button where all media becomes visible.

**Comment by shumvgolove** [comment] 2023-04-26 12:56
Duplicate of https://github.com/simplex-chat/simplex-chat/issues/1899

**Closed by shumvgolove** 2023-04-26 12:56 UTC
