### ISSUE TITLE
Bluetooth earbud / headset not detected

### ISSUE THREAD

**Issue by kavemang** [simplex-chat/simplex-chat#886] opened 2022-08-03 20:34 UTC
Hi, this could be intended not sure

When using video call the current sound device is not used, instead the phone speaker and mic is used only and bluetooth earbuds for example are ignored

**Comment by shumvgolove** [comment] 2022-11-21 11:57
Duplicate of https://github.com/simplex-chat/simplex-chat/issues/1043

**Closed by shumvgolove** 2022-11-21 11:57 UTC
Labels: bug
