### ISSUE TITLE
[Bug]: 6.0.3 group chat: rcvGroupEvent > memberProfileUpdated causes wrong chatStats.unreadCount

### ISSUE THREAD

**Issue by tomquas** [simplex-chat/simplex-chat#4925] opened 2024-09-23 12:04 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Platform

Android, iOS

### OS version

Android 14, ios 17.x

### App version

core libs 6.0.3

### Current Behavior

context: 
  - we're integrating simplex chat libs in our own product, this ticket is not about the simplex chat app!
  -  we are talking about group chats

what's happening?

1. user A changes the group profile by sending a CC.updateGroupProfile; the update is delayed until A sends an additional text or media message (delay indented? bug?)
2. A sends both text and memberProfileUpdated messages to B
3. B received text and memberProfileUpdated (in this order... wouldn't it be better the other way round? switching them would a) represent the chronological order of actions correctly, and b) prevent CC.apiChats to return a message with content 'updated profile' and instead show the text message)
4. each subsequent CC.apiChats returns chatStats.unreadCount = 1 and chatStats.unreadChat = false for that chat room
5. sending APIChatRead for that chat does not change this behavior, only sending another text or media message fixes this behavior

### Expected Behavior

1. memberProfileUpdated message should be in order with text message from the example above
2. memberProfileUpdated message should not cause CC.apiChats to return wrong chat state; see above
3. memberProfileUpdated message should be sent without delay or the need for an extra message

### Steps To Reproduce

_

### Relevant log output

```shell
result of CC.apiChats with privacy-related info replaced:

"chatInfo":
{
    "type": "group",
    "groupInfo":
    {
        ...
    }
},
"chatItems":
[
    {
        "chatDir":
        {
            "type": "groupRcv",
            "groupMember":
            {
                "groupMemberId": 2,
                "groupId": 1,
                "memberId": "QmtJbW5WazBmU3hJY0hRWQ==",
                "memberRole": "member",
                "memberCategory": "invitee",
                "memberStatus": "connected",
                "memberSettings":
                {
                    "showMessages": true
                },
                "blockedByAdmin": false,
                "invitedBy":
                {
                    "type": "user"
                },
                "invitedByGroupMemberId": 1,
                "memberProfile":
                {
                    "profileId": 2,
                    ...
                },
                "memberContactProfileId": 2,
                "memberChatVRange":
                {
                    "minVersion": 1,
                    "maxVersion": 9
                }
            }
        },
        "meta":
        {
            "itemId": 42,
            "itemTs": "2024-09-23T11:27:24.554180038Z",
            "itemText": "updated profile",
            "itemStatus":
            {
                "type": "rcvRead"
            },
            "itemEdited": false,
            "deletable": false,
            "editable": false,
            "createdAt": "2024-09-23T11:27:24.554180038Z",
            "updatedAt": "2024-09-23T11:27:24.554180038Z"
        },
        "content":
        {
            "type": "rcvGroupEvent",
            "rcvGroupEvent":
            {
                "type": "memberProfileUpdated",
                "fromProfile":
                {
                    ...
                },
                "toProfile":
                {
                    ...
                }
            }
        },
        "reactions":
        []
    }
],
"chatStats":
{
    "unreadCount": 1,
    "minUnreadItemId": 43,
    "unreadChat": false
}
```

**Comment by spaced4ndy** [comment] 2024-09-25 17:42
fixed in #4940. delayed sending of profile update in groups is by design, to decrease immediate client load of sending it to all member connections across all groups

**Closed by spaced4ndy** 2024-09-25 17:42 UTC
Labels: bug, triage
