### ISSUE TITLE
Unable to Make Voice Calls With Simplex 4.2

### ISSUE THREAD

**Issue by PackMeister** [simplex-chat/simplex-chat#1344] opened 2022-11-10 19:48 UTC
Just did some testing this AM with another user of Simplex 4.2 on Android, one of us running GrapheneOS the other CalyxOS.

Chat and file xfers from camera, file selection or gallery work well.

However we're still unable to get live calls between us to work.

We can initiate calls to each other but we both get messages are clients are trying to connect.

Are additional Android permissions and/or Simplex settings required to enable Simplex 4.2 voice and/or video calling?

**Comment by epoberezkin** [comment] 2022-11-11 07:57
We are investigating this issue - it does affect some users.

could you please connect to me via the chat (connect to developers) - I’d explain what could be checked on your end to diagnose the issue?

**Comment by shumvgolove** [comment] 2022-11-21 12:25
Duplicate of https://github.com/simplex-chat/simplex-chat/issues/1230

**Closed by shumvgolove** 2022-11-21 12:25 UTC
Labels: duplicate
