### ISSUE TITLE
Unable to install on Android 10's Go edition

### ISSUE THREAD

**Issue by jnolan7599** [simplex-chat/simplex-chat#1726] opened 2023-01-12 01:31 UTC
Hello, I have a [Alcatel 1B (2020)](https://www.gsmarena.com/alcatel_1b_(2020)-10019.php). Quad-core 1.3 GHz Cortex-A53 with 2GB RAM, I'm unable to install v4.4.0 as it states it's incompatible. Running Android 10's Go edition, is there anything I can do to install this, even as a sideloaded APK?

**Comment by el-coder-sb** [comment] 2023-01-12 08:49
In F-Droid it´s shown as incompatible as well. (LingeageOS based on Anroid 10).

**Comment by epoberezkin** [comment] 2023-01-12 14:43
It's probably a duplicate of https://github.com/simplex-chat/simplex-chat/issues/538, so will close this one!

We're now working to add 32bit CPU support – thank you for the patience!

**Comment by epoberezkin** [comment] 2023-01-12 14:44
you can check your CPU mode in z-cpu app, but I am pretty certain it's 32bt on that device... Sorry!

**Closed by epoberezkin** 2023-01-12 14:43 UTC

**Comment by jnolan7599** [comment] 2023-01-12 20:36
@epoberezkin 

Interesting but to my dismay:

> Built as a low-power processor with 64-bit capabilities, [...]
&mdash; Cortex A53, ARM Holdings, https://www.arm.com/products/silicon-ip-cpu/cortex-a/cortex-a53

SOC is a Qualcomm Snapdragon 425 MSM8917 but the device specs for the ABI is showing as _armeabi-v7a_... so a 32-bit OS on 64-bit hardware. I'll follow #534.

**Comment by epoberezkin** [comment] 2023-01-12 21:25
Yes, it is quite annoying - they take 64bit CPUs and lock them into 32bit mode, probably to save battery...

Sorry about not supporting it yet!
