### ISSUE TITLE
Calls not connecting, messages instant

### ISSUE THREAD

**Issue by gitbq** [simplex-chat/simplex-chat#1230] opened 2022-10-20 01:28 UTC
I have been testing on ios and android devices. Messages are received instantly (~20 seconds).

However calling almost impossible to connect. 

Ios to ios will connect rarely. It goes through all the steps but mostly just hangs on there "connecting" screen. Android to and from ios always hangs on this "connecting" screen.

On ios to ios, if i can get to the "connected" screen , only about 40% of the time is the call actually connected.

Devices:
iPad: wifi V:4.0(78)
iPhone: 4g V:4.0(78)
Pixel, Calyx: 4G. V:4.1(62), also tried v:4.0

**Comment by epoberezkin** [comment] 2022-10-20 09:24
There are three reasons it might be happening:

1. the network timeout is longer than our server is happy about. On the first phase of connection it can be 60 second, but on the second phase it's about 10, and `coturn` doesn't seem to allow increasing it... We need to try some other STUN/TURN server, probably, and it would help a lot if you could debug it together with me, so I can see what is happening in the server log during the connection.
2. some network/firewall restrictions - again, we could debug together to see in the server logs how far the connection progresses and what gets blocked. Try connecting on another network (e.g. wifi)
3. the recent iOS regression when they lost support for insertable streams in iOS 15.7 (it works in iOS 16 though) and the bug in Android that refuses to accept the unencrypted call. It doesn't seem to be the case from what you are describing - my understanding is that both phones show black "connecting" screen. If that's the case this is not the reason, and it will be fixed in the next release anyway (on Android, not much we can do about iOS encryption support).

**Comment by epoberezkin** [comment] 2022-10-20 09:24
... please let me know if you have time / able to debug together.

Thank you for reporting it anyway!

**Comment by gitbq** [comment] 2022-10-21 00:37
As it seems to be a known problem / limitation, I'm happy to leave it for now.
I might wait for the next few updates before revisiting this aspect. 
Thanks again!

**Comment by epoberezkin** [comment] 2022-10-22 06:49
Not really a “known” problem. A small njmber of users seems to be experiencing it and we don’t do anything to fix. Those were just theories, but I don’t really know what causes it.

**Comment by gitbq** [comment] 2022-10-27 14:52
No worries. If you world like me to send through any information, please let me know.

**Comment by epoberezkin** [comment] 2022-10-27 14:54
what would help if we could debug it together - e.g. you would try to call me at agreed time and I would look at the server logs at the same time to see why it's not connecting.

**Comment by gitbq** [comment] 2022-10-27 15:15
Ok. I'll try tomorrow. I should be available between 12-15 hours from now . I'll contact you there.

**Comment by andreasmjg** [comment] 2022-11-05 08:55
Hi, I'd be happy to help debug as well. Have the same issue.

**Comment by ioerror** [comment] 2022-11-18 14:54
I have found that between iOS and Android (current AppStore and current f-droid releases) does not connect at all for me. With relay and without relay, same result. Willing and able to help debug this problem.

**Comment by govinda17** [comment] 2022-12-13 04:11
I have exactly the same problem. I am using ios and my friend is using graphene.
On his side also the name/screen is not visible just some faded yellow colors that are not readable when trying to make a call.
Also please make an option that u can press and lift up the microphone symbol in order to speak (like signal and all other apps) and just hit send when u want to send it. If you are sending a longer voice message you should keep holding the recording toogle for too long, not practical at all.

**Comment by gitbq** [comment] 2023-02-04 05:47
I have traveled to another country and run new tests with ios app v4.4 and Android app v4.5 and am happy to say that calling seems to be  working reliably on ios, vanilla Android and Graphene devices.

Unfortunately my calyxos device just will not connect. One forum Grapheneos user mentioned he had problems with Rethink DNS app and that in "rethinkDNS  app firewall settings, you need to turn off "block UDP except DNS and NTP". The call will only show " connecting" if that setting is enabled in RethinkDNS. "
However my calyxos device doesn't have this installed but I'm guessing there is a setting there that is blocking the calling somehow.

**Comment by epoberezkin** [comment] 2023-02-04 23:18
it will be fixed in v4.5.1

**Comment by gitbq** [comment] 2023-02-06 05:12
I just installed v4.5.1 and it works flawlessly on the calyxos device also.
Thanks again!!

**Closed** 2023-02-06 05:12 UTC
Labels: bug, ios, android

**Comment by epoberezkin** [comment] 2023-02-06 08:28
Cool! Nothing to do with OS or the device, it was our mistake not to add fallback to TCP in case UDP is blocked by the provider, we incorrectly assumed that falling back to TCP is the default. Some comment in users group helped - it was like "it works perfectly, you just need to allow UDP..." :)

https://github.com/simplex-chat/simplex-chat/pull/1892/files#diff-565eb6a89167855df198fb95ef679463978030c63b0748779eb32c6d9ed89743R222 - this change, in particular, just one line to add server falling back to TCP in case UDP is not available, while preserving UDP when it is. UDP should result in higher call quality, so allowing it (it your VPN, provider, proxy, whatever) is still helpful, when it is possible.
