### ISSUE TITLE
Group messages are delivered out-of-order when catching up

### ISSUE THREAD

**Issue by neutralinsomniac** [simplex-chat/simplex-chat#918] opened 2022-08-09 10:40 UTC
If a device is offline for a while, and a bunch of messages come through in a group while the device is offline, once the offline device comes back online, it receives all the messages it missed, but the order of the messages seems to be random.

**Comment by epoberezkin** [comment] 2022-08-09 11:49
As they say, it’s a feature not a bug :)…
As all messages are sent in separate connections they will be added in the order of arrival. We could, theoretically, insert them into the view in the same order as when they are retrieved from the database… Need to think if it’s a good idea.

**Comment by epoberezkin** [comment] 2022-10-25 09:00
The messages are sorted by the message time (received time for received messages, server time for sent messages), so it only causes clock issues for the recipient who has unsynched clock, not to others, so it's rare.

The problem is that when you have the conversation open they are added to the bottom, so you don't miss them, they'll only get sorted after you re-open the chat.

The only real solution for sorting prior to the delivery would be to have a hosted group - something we plan to add to support large groups.

**Comment by epoberezkin** [comment] 2022-10-26 07:35
This already happens when you open the group - they are displayed in the correct order.

When you are in the group approach this doesn’t seem the best approach as it’s not clear for how long they should be collected before they are shown, so they are just shown in the order of arrival and appended to the bottom. They are ordered within each member, but between members they can arrive in any order, and catching up may take arbitrary time. So what you are suggesting is that the client should wait and show no messages until they stop arriving, in which case the user would be likely to think it’s simply not working…

**Comment by epoberezkin** [comment] 2022-11-25 22:33
this will be addressed with hosted groups, we won't be improving delivery ordering for current decentralized secret groups, not for now at least. Closing it.

**Closed by epoberezkin** 2022-11-25 22:33 UTC
Labels: enhancement
