### ISSUE TITLE
SimpleX lock bug

### ISSUE THREAD

**Issue by Wjxfi** [simplex-chat/simplex-chat#1783] opened 2023-01-17 07:29 UTC
Exited the application. Opened the app after a while. 1 second or less, the screen displays where I left off. blocked the app.

**Comment by epoberezkin** [comment] 2023-01-17 09:26
not sure what it's about. is it on iOS?

**Comment by x80486** [comment] 2023-01-17 15:30
I second this one. It was always weird that it didn't happen to anyone else, so I thought it was a problem with my device...but it's true, `SimpleX` actually shows the "protected" content for a small period of time, on or about a second.

**Comment by avently** [comment] 2023-01-23 11:58
I think it's device specific thing, but there is something I can do in order to make the process faster on app's side. 
Made a PR #1822, will see if it makes any difference in your case. If not, other technique needs to be applied.

**Comment by epoberezkin** [comment] 2023-03-18 22:41
@Wjxfi are you able to install test APK? We could then make a build from #1822.

This is certainly a problem caused by the combination of app and device, as we couldn't reproduce this issue on either of devices that we have, but that PR might improve it for your device.

What is the exact device model?

**Comment by epoberezkin** [comment] 2023-03-21 08:38
https://upload.disroot.org/r/n0sAYNkT#P3WsAjQmeFTyQuAogQsWZROmS21dsdylWjj4mvcA1mI=

This should be an APK that adds one commit to the currently released version, but make sure to back up the current database before installing it (depending on where you installed it before, you might need to export/import database anyway, as the signing key can be different). Also, please make sure that you can reproduce the issue with the current build on the same database that you will be testing this build with (e.g., if you are going to test on empty database, make sure the issue is reproducible on empty database, not to claim victory too early).

**Comment by epoberezkin** [comment] 2023-03-22 08:50
sorry, so you say it's fixed with the new APK?

**Closed as completed** 2023-04-22 10:01 UTC
