### ISSUE TITLE
Secrets get shown in plaintext!!

### ISSUE THREAD

**Issue by dtuando** [simplex-chat/simplex-chat#438] opened 2022-03-14 06:14 UTC
Here is the bug:
(Android 12 |  Pixel 5)
I sent myself a secret message from my PC via CLI and the secret displays in the notification on the lock screen in plain text.

**Comment by shumvgolove** [comment] 2022-03-14 06:28
Duplicate of #416

New release with the fix is coming next week.

**Closed by shumvgolove** 2022-03-14 06:28 UTC

**Comment by dtuando** [comment] 2022-03-14 06:45
my apologies! I should have looked in the closed!
