### ISSUE TITLE
[Bug] Anyone in a public group can contact (DM) another member without an invitation request

### ISSUE THREAD

**Issue by serrq** [simplex-chat/simplex-chat#1326] opened 2022-11-08 19:16 UTC
I find that this practice is the denial of what is written on the website and that is "SimpleX is immune to spam". Well it is not so: within public groups a member can write to another member without receiving permission (invitation link).

For me this is a serious bug.

I personally received direct message from the admin without my approval. I don’t want any exceptions. No one can write to me until I’ve invited him.

As for blocking actions, these are missing altogether: either mute notifications or delete contact. Imagine having to delete 200 contacts in a group that they write to you without your permission. Hallelujah.

As a first act of defense I abandoned all public groups: if everyone can write to me then those are not safe places for me.

**Comment by epoberezkin** [comment] 2022-11-08 20:40
I understand the unhappiness about this feature, this is not a bug though - this is by design.

We are considering to change it, the design where members can send direct messages doesn't really fit the concept of public groups, that joining via the link implies.

Thanks for feedback, this is helpful.

**Comment by epoberezkin** [comment] 2022-11-08 21:14
For now, until we change it, I will add a note about it where we published group links, so that it's not a surprise.

**Comment by epoberezkin** [comment] 2022-11-10 09:19
Yep, that’s clear. We will be making it a group setting and making it clear in the invitation whether DMs are allowed or not… not sure yet what to do about the existing groups, will think about it.

**Comment by DeMoN100** [comment] 2022-11-10 12:43
> > Instead of showing the user whether DMs are allowed or not, this could also be a check box, to let him choose. The user would be able to change this setting later. The default of this check box could be set by some heuristic (number of members, was the invitation by link or direct). A group setting could also be used to choose the default but I'm not sure this is necessary then.
> 
> I respect your opinion but objectively how do you put to the group administrators, as default, the decision whether or not you can contact me in DM? If you allow me this is just my choice. Anything that moves in towards my profile (as in yours) is my (or your) choice. We do not do the end of emails where to unsubscribe from a harasser newsletter you have to send a request to the harasser and hope that he will stop. In default the choice is always the lesser evil, and this is clearly "do not disturb me".
> 
> This is only my personal opinion.

I think what he mean't by this was a checkbox to allow dms from anyone in your settings & if unchecked then they need to be a contact to DM you.

With that in mind you could make a return window pop up saying "This user does not have dms from anyone enabled you must add them as a contact to message them."

**Comment by epoberezkin** [comment] 2023-04-14 15:05
closing, it's now a group setting

**Closed by epoberezkin** 2023-04-14 15:05 UTC
Labels: enhancement
