### ISSUE TITLE
[Feature requests] Add a "themed icon"

### ISSUE THREAD

**Issue by WX4300** [simplex-chat/simplex-chat#1853] opened 2023-01-29 00:24 UTC
The app needs support for the "themed icons" feature present in the newest android version

![Screenshot_20230129-012041_crDroid Home](https://user-images.githubusercontent.com/113265063/215297246-9cbef301-4075-4d1e-abbc-5d2d60b82bb5.png)

**Comment by epoberezkin** [comment] 2023-04-01 18:53
duplicate of #1301?

**Closed as completed** 2023-04-26 12:36 UTC
Labels: duplicate
