### ISSUE TITLE
[Feature]: Make it possible to use one account from multiple devices (ie: desktop, mobile, laptop, etc)

### ISSUE THREAD

**Issue by nihilist001** [simplex-chat/simplex-chat#5041] opened 2024-10-14 11:18 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Platform

Linux, Mac, Windows, Android, iOS, all

### App version

latest

### Feature

there should be a reliable (and easy) way of using one simplex account from multiple devices:
- master device with the account (on desktop for example)
- secondary device (on mobile for example): you should be able to use the master account on your desktop from your mobile, and without the "same network" requirement, totally unecessary, unless if i'm missing something
- Just allow to do that over any simplex relay server, with a validation mechanism to be done from the master device to authorize (or decline) the synchronisation.

idea:
- on the master device account you create a "use this account from another device" QR code / link
- on that secondary device when you click "create account" you should have the option to "use an account from another device"
- scan that QR code, and then you need to confirm the device sync request from the master account. (just make the verification process include the already existing "verify security code" to make sure the request is valid)
- and from there you should be able to use the account that is on your desktop, from your mobile device. 

this is starting to look stupid to require N accounts when you have N devices "user, user-phone, user-desktop, user-laptop" it's a major drawback since you need to check all devices for new private messages or requiring to make a group chat just to make sure all of your devices recieve the private messages.

i think this one should be explicitely put on the roadmap, because look at everyone coming from other chat apps that are expecting this feature to be there, it might deter them from switching to simplex

**Comment by Martina-Neumayer** [comment] 2024-10-14 17:16
Great idea! This existing way to connect two devices is very unfriendly. Especially when the apps versions are so often released. And for example AUR one is still outdated because maintainer does not want to compile pre-release versions of the Arch desktop app. Where connecting two different versions of the application is not possible.
This situation is very impractical for users. Especially those who cannot compile the application package themselves.

**Comment by egrieco** [comment] 2024-10-14 21:59
If running device firewalls like OpenSnitch/LittleSnitch and NetGuard, getting devices linked and keeping them linked is near impossible.

Modern communication systems should recognize that a digital identity is likely to span multiple devices.

**Comment by nihilist001** [comment] 2024-10-15 06:30
> If running device firewalls like OpenSnitch/LittleSnitch and NetGuard, getting devices linked and keeping them linked is near impossible.
> 
> Modern communication systems should recognize that a digital identity is likely to span multiple devices.

since simplex supports .onion traffic i don't see the issue. locally just make the user connect to the local SOCKS5 proxy on 127.0.0.1 on port 9050 and then make it publish a hidden service (ndzqjqoziufj...onion:7070) and there will be a permanent way of accessing the master account without requiring any port forwarding of any kind.

**Comment by nihilist001** [comment] 2024-10-15 06:40
> Can be the master device renegotiated afterwards? If for example one changes its mind?

there should be a "revoke access" or "manage devices" setting somewhere, for a particular account yeah

**Comment by martin-braun** [comment] 2024-10-20 06:48
In the current state of affair, what happens if you lose or break your master device? Right now, the only way to combat this is to regularly export the database on a different device.

Also this issue is a duplicate of #444, we shouldn't open new issues, the old one isn't even closed.

**Closed as not planned** 2024-10-22 14:10 UTC
Labels: duplicate, enhancement
