### ISSUE TITLE
[Feature]: Incognito keyboard mode feature in privacy options

### ISSUE THREAD

**Issue by User1l0** [simplex-chat/simplex-chat#2617] opened 2023-06-26 21:10 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Platform

Android

### App version

5 1.3

### Feature

.

**Comment by Mikaela** [comment] 2023-07-02 07:50
Duplicate of https://github.com/simplex-chat/simplex-chat/issues/1545

**Closed as not planned** 2024-05-07 07:34 UTC
Labels: enhancement, triage
