### ISSUE TITLE
WindowsCli

### ISSUE THREAD

**Issue by redbaron721** [simplex-chat/simplex-chat#422] opened 2022-03-10 12:10 UTC
Can't mark the invitation link in the client it to send to another user.

**Comment by epoberezkin** [comment] 2022-03-12 07:40
not sure I understand what you mean? You should be able to select and copy text from all terminal applications - do you mean the links are not clickable? If so, this is not something that we have any control over - it's completely defined by the terminal software you use...

**Comment by z8512** [comment] 2022-03-16 03:29
Can't reproduce.
You should use a better terminal like Windows Terminal/mintty or Alacritty. You can't select text in Command Line or Powershell.
Close this issue

**Closed** 2022-03-16 06:54 UTC
